[package]
name = "hstreamdb-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"

once_cell = "1.15.0"

anyhow = "1.0.62"
rand = "0.8.5"
testcontainers = "0.14.0"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
