[package]
name = "hstreamdb-test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"

anyhow = "1.0.68"
rand = "0.8.5"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
