[package]
edition = "2021"
name = "hstreamdb-pb"
version = "0.1.0"

[dependencies]
workspace-hack = { version = "0.1", path = "../utils/workspace-hack" }

prost = "0.11.0"
prost-types = "0.11.1"
tonic = "0.8.0"

[build-dependencies]
tonic-build = "0.8.0"
